services:
  api:
    # Thay 'kailearndev' bằng username GitHub của ông
    image: ghcr.io/kailearndev/fake-book-api:latest
    container_name: fake_book_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - fake_book_network

networks:
  fake_book_network:
    external: true